<h3>Vendors</h3>
<table class="center">
<tr>
	<td class="label">Day</td>
	<td class="label">Breakfast</td>
	<td class="label">Lunch</td>
	<td class="label">Late Night</td>
</tr>
<tr>
	<td class="label">Monday</td>
	<td class="vendor">Order Up (Fan)<br />Leticia's (Phase 3)</td>
	<td class="vendor">Zedric (Fan)<br />Grant Street Pizza (Phase 3)</td>
	<td class="vendor">Say She Ate (Phase 1)</td>
</tr>
<tr>
	<td class="label">Tuesday</td>
	<td class="vendor">Taste Crepes (Fan)<br />Chick-fil-A (Phase 3)</td>
	<td class="vendor">The Lion & Rose (Fan)<br />China Garden (Phase 3)</td>
	<td class="vendor">&nbsp;</td>
</tr>
<tr>
	<td class="label">Wednesday</td>
	<td class="vendor">Leticia's (Fan)<br />Zedric (Phase 3)</td>
	<td class="vendor">Little Jamaica (Fan/Cash)<br />Chick-fil-A (Phase 3)</td>
	<td class="vendor">&nbsp;</td>
</tr>
<tr>
	<td class="label">Thursday</td>
	<td class="vendor">Order Up (Fan?)<br />Taste Crepes (Phase 3)</td>
	<td class="vendor">Leticia's (Fan)<br />Rudy's (Phase 3</td>
	<td class="vendor">&nbsp;</td>
</tr>
<tr>
	<td class="label">Friday</td>
	<td class="vendor">Leticia's (Fan)<br />Chick-fil-A (Phase 3)</td>
	<td class="vendor">Smoke Shack, Rick Shaw, Rocker Dogz, Cheesy Janes and Say•She•Ate (Phase 1 or Garage)<br />McAlisters (Phase 3)</td>
	<td class="vendor">&nbsp;</td>
</tr>
</table>
